version: '3.7'

services:

  db:
    image: postgres:11.2
    volumes:
      - .volumes/db_data/:/var/lib/postgresql/data/
    env_file:
      - .env
    expose:
      - "5432"

  bot:
    image: diraven/main:crabot-bot
    init: true
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: diraven/main:crabot-frontend
    init: true
    depends_on:
      - db
    ports:
      - "80:80"
    env_file:
      - .env
