version: '3.3'

services:

  postgres:
    image: postgres:11.2
    volumes:
      - .volumes/postgres/:/var/lib/postgresql/data/
    env_file:
      - .env
    expose:
      - "5432"

  app:
    image: diraven/main:crabot-app
    depends_on:
      - postgres
    ports: ['8002:80']
    env_file:
      - .env

  bot:
    image: diraven/main:crabot-bot
    depends_on:
      - postgres
      - app
    env_file:
      - .env
