version: '3.7'

services:

  db:
    image: postgres:11.2
    volumes:
      - .volumes/db_data/:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  bot:
    build: bot
    entrypoint: ./docker-entrypoint.bash
    command: python main.py
    depends_on:
      - db
    volumes:
      - ./bot:/app
    init: true
    env_file:
      - .env

  frontend:
    build: frontend
    entrypoint: ./docker-entrypoint.bash
    command: ./manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - ./frontend:/app
    ports:
      - "8000:8000"
    init: true
    env_file:
      - .env
