version: '3.3'

services:

  db:
    image: postgres:11.2
    volumes:
      - .volumes/db_data/:/var/lib/postgresql/data/
    env_file:
      - .env
    expose:
      - "5432"

  bot:
    image: diraven/main:crabot-bot
    depends_on:
      - db
      #    init: true
    env_file:
      - .env

  frontend:
    image: diraven/main:crabot-frontend
    depends_on:
      - db
    ports:
      - "8123:8000"
      #    init: true
    env_file:
      - .env
