version: '3.3'

services:

  postgres:
    ports:
      - '5432:5432'

  bot:
    build:
      context: bot
      dockerfile: Dockerfile_dev
    volumes:
      - ./bot:/app
      - ./.volumes/root:/root


  app:
    build:
      context: app
      dockerfile: Dockerfile_dev
    ports: ['80:80']
    volumes:
      - ./app:/app
      - ./.volumes/root:/root
