version: '3.7'

services:

  db:
    ports:
      - '5432:5432'

  bot:
    build:
      context: bot
      dockerfile: Dockerfile_dev
    volumes:
      - ./bot:/app
      - ./.volumes/root:/root


  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile_dev
    volumes:
      - ./frontend:/app
      - ./.volumes/root:/root
