version: '3.3'

services:

  db:
    ports:
      - '5432:5432'

  bot:
    build: bot
    depends_on:
      - db
    volumes:
      - ./bot:/app
#    init: true
    env_file:
      - .env

  frontend:
    build: frontend
    depends_on:
      - db
    volumes:
      - ./frontend:/app
    ports:
      - "8000:8000"
#    init: true
    env_file:
      - .env
