databases:
  default:
    host: ''
    user: ''
    password: ''
    name: ''

helpscout:
  app_id: ''
  app_secret: ''

sentry_io:
  dsn: ''

debug: 'true'

allowed_hosts:
  - '127.0.0.1'
  - '0.0.0.0'
